[package]
name = "forge-search"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
ignore = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
