[package]
name = "forge-input"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
smallvec = { workspace = true }
arboard = { workspace = true }
